### ISSUE TITLE
Match: on the match/group stats make a player alias into link to /players

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwprostats-ui#44]
![image](https://user-images.githubusercontent.com/10265890/140400699-e8c55a33-ae84-4317-905a-f72368755190.png)

**Comment by utrolig** [comment]
https://github.com/rtcwmp-com/rtcwprostats-ui/pull/45

**Comment by donkz** [comment]
Need to add functionality that says
if playerid starts with 8e6a51baf1c7e338a118d9e32472954 or 58e419de5a8b2655f6d48eab68275db - do nothing
?

These are shared guids and stats are mingled or will simply not work 
Also, it would be nice to have some * or icon next to those 2
